@startuml
'https://plantuml.com/class-diagram

@startuml
'https://plantuml.com/class-diagram

title Search Aircraft by Model/Status/Manufacturing Year: Architecture — Class Diagram

package "Searching" <<rectangle>> {
    class Aircraft <<Aggregate Root>> {
        - String name
        - int seating_capacity
        - double max_range
        - double fuel_capacity
        - double cruising_speed
        - Set<String> feature
        - AircraftManufacturer manufacturer
    }
    interface AircraftRepository {
        + Optional<List<Aircraft>> findByParameter(aircraft_model.name)
        + Optional<List<Aircraft>> findByParameter(status)
        + Optional<List<Aircraft>> findByParameter(manufacturing_date)
    }
    class SearchAircraftByIataUseCase <<@UseCase>> {
        + List<Aircraft> execute(aircraft_model.name)
        + List<Aircraft> execute(status)
        + List<Aircraft> execute(manufactoring_date)
    }

    SearchAircraftByIataUseCase ..> AircraftRepository : findByParameter()
}

@enduml