@startuml
title Register an Aircraft — POST /aircraft

autoactivate on

actor ATCC
participant AircraftController
participant RegisterAircraftUseCase <<@UseCase>>
participant RegisterAircraftService <<Domain Service>>
participant AircraftRepository
participant AircraftManufacturerRepository

ATCC -> AircraftController : POST /aircraft\n{\n\tregistration_number: "N737UA",\n\tmodel_name: "Boeing 737",\n\tmanufacturing_date: "2025-05-16",\n\tlast_maintenance: "2025-05-16",\n\tmax_flight_hours_until_maintenance: 200,\n\tmax_days_until_maintenance: 150,\n\teconomy_seats: 150\n\tpremium_economy_seats: 70\n\tbusiness_seats: 35\n\tfirst_seats: 15\n\tstatus: "AVAILABLE"\n}

AircraftController -> AircraftController : extract username from JWT
alt "User has authorization"
    AircraftController -> RegisterAircraftUseCase : execute(registration_number, model_name, manufacturing_date, last_maintenance, max_flight_hours_until_maintenance, max_days_until_maintenance, economy_seats, premium_economy_seats, business_seats, first_seats, status)
        RegisterAircraftUseCase -> AircraftModelRepository : findByNameAndSeatingCapacity(model_name, economy_seats + premium_economy_seats + business_seats + first_seats)
        alt "The model exists"
        AircraftModelRepository --> RegisterAircraftUseCase : aircraft_model_object
        RegisterAircraftUseCase -> RegisterAircraftUseCase : new AircraftRegistration(registration_number)
        RegisterAircraftUseCase --> RegisterAircraftUseCase : aircraft_registration
        RegisterAircraftUseCase -> RegisterAircraftUseCase : AircraftStatus.valueOf(status)
        RegisterAircraftUseCase --> RegisterAircraftUseCase : aircraft_status
        RegisterAircraftUseCase -> RegisterAircraftUseCase : new SeatingConfiguration(economy_seats, premium_economy_seats, business_seats, first_seats)
        RegisterAircraftUseCase --> RegisterAircraftUseCase : seating_configuration
        RegisterAircraftUseCase -> RegisterAircraftService : register(aircraft_registration, aircraft_model_object, manufacturing_date, last_maintenance, max_flight_hours_until_maintenance, max_days_until_maintenance, seating_configuration, aircraft_status)
            RegisterAircraftService -> AircraftRepository : alreadyExists(aircraft_registration)
            AircraftRepository --> RegisterAircraftService : false
            RegisterAircraftService -> RegisterAircraftService : new Aircraft(aircraft_registration, aircraft_model_object, manufacturing_date, last_maintenance, max_flight_hours_until_maintenance, max_days_until_maintenance, seating_configuration, status)
        RegisterAircraftService --> RegisterAircraftUseCase : aircraft (unsaved)
        deactivate
        RegisterAircraftUseCase -> AircraftRepository : save(aircraft)
        AircraftRepository --> RegisterAircraftUseCase : aircraft (persisted)
    RegisterAircraftUseCase --> AircraftController : aircraft
AircraftController --> ATCC : 201 Created\n{ aircraft.registration_number, _links.return }
        else "The aircraft model does not exist in the system"
AircraftController --> ATCC : 400 Bad Request\n{ message: "The request's data is malformed" }
        end

else "User does not have authorization"
AircraftController --> ATCC : 401 Unauthorized\n{ message: "The user does not have valid credentials for this action" }
end

@enduml