### Login - Backoffice
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "username": "backoffice",
  "password": "1234"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### Login - ATCC
POST http://localhost:8080/api/login
Content-Type: application/json

{
"username": "atcc",
"password": "1234"
}

> {%
    client.global.set("auth_token", response.body.token);
%}

### US 106 - Registar Aeroporto (Backoffice)
POST http://localhost:8080/api/airports
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Aeroporto de Teste",
  "iata": {
    "iata": "OPO"
  },
  "coordinates": {
    "longitude": -8.9,
    "longitude_direction": "W",
    "latitude": 38.7,
    "latitude_direction": "N"
  },
  "airport_location": {
    "city": "Porto",
    "country": "Portugal",
    "region": "Europa"
  },
  "airport_type": "Civil",
  "time_zone": "GMT",
  "status": "OPERATIONAL",
  "operational_hours": {
    "opening_hours": 6,
    "closing_hours": 23
  },
  "runway_info": [
    {
      "name": "03/21",
      "length": 3805.0,
      "orientation": {
        "orientation": "NE"
      }
    }
  ],
  "contact_info": [
    {
      "type": "EMAIL",
      "contact": "geral@aeroporto.pt",
      "description": "Contacto Geral"
    }
  ],
  "terminals": [
    { "terminal": "T1" }
  ],
  "gates": [
    { "gate": "G42" }
  ],
  "services": [
    { "service": "Free Wi-Fi" }
  ],
  "images": []
}

### US 106 - Registar Aeroporto 2 (Backoffice)
POST http://localhost:8080/api/airports
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Aeroporto Humberto Delgado",
  "iata": {
    "iata": "LIS"
  },
  "coordinates": {
    "longitude": -9.135,
    "longitude_direction": "W",
    "latitude": 38.774,
    "latitude_direction": "N"
  },
  "airport_location": {
    "city": "Lisboa",
    "country": "Portugal",
    "region": "Europa"
  },
  "airport_type": "Civil",
  "time_zone": "GMT",
  "status": "OPERATIONAL",
  "operational_hours": {
    "opening_hours": 0,
    "closing_hours": 24
  },
  "runway_info": [
    {
      "name": "03/21",
      "length": 3805.0,
      "orientation": {
        "orientation": "NE"
      }
    }
  ],
  "contact_info": [],
  "terminals": [],
  "gates": [],
  "services": [],
  "images": []
}

### US 101- Criar Modelo de Avião (Backoffice) - Lucas
POST http://localhost:8080/api/aircraft-model
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Boeing 737",
  "seating_capacity": 189,
  "max_range": 5000.0,
  "fuel_capacity": 20000.0,
  "cruising_speed": 850.0,
  "manufacturer_name": "Boeing"
}


### US 106a - Adicionar Certificação de Avião a um Aeroporto (Os dois)
PUT http://localhost:8080/api/airports/OPO/certifications
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Boeing 737"
}


### US 107 - Ver os detalhes do aeroporto por um IATA (Os dois)
GET http://localhost:8080/api/airports/OPO
Authorization: Bearer {{auth_token}}


### US 108 - Pesquisar Aeroportos por Cidade (ATTC)
GET http://localhost:8080/api/airports?city=Porto
Authorization: Bearer {{auth_token}}

### US 108 - Pesquisar Aeroportos por País (ATTC)
GET http://localhost:8080/api/airports?country=Portugal
Authorization: Bearer {{auth_token}}

### US 108 - Pesquisar Aeroportos por Nome (ATTC)
GET http://localhost:8080/api/airports?name=Aeroporto%20Humberto%20Delgado
Authorization: Bearer {{auth_token}}

### US 108 - Listar Todos os Aeroportos (ATCC)
GET http://localhost:8080/api/airports
Authorization: Bearer {{auth_token}}


### US 109 - Atualizar Status do Aeroporto (Backoffice)
PATCH http://localhost:8080/api/airports/OPO
Content-Type: application/json
Authorization: Bearer {{auth_token}}

 {
   "status": "CLOSED"
 }
