@startuml
'https://plantuml.com/class-diagram

title View Aircraft Status in Real Time: Architecture — Class Diagram

package "Aircraft Aggregate" <<rectangle>> {
    class Aircraft <<Aggregate Root>> {
        - AircraftRegistration registration_number
        - AircraftManufacturer manufacturer
        - AircraftModel model
        - SeatingConfiguration seating_configuration
        - Date manufactoring_date
        - Date last_maintenance
        - int days_since_last_maintenance
        - int max_flight_hours_until_maintenance
        - int max_days_until_maintenance
        - AircraftStatus status
        - String image
        ---
        + AircraftStatus obtainStatus()
    }
    interface AircraftRepository {
        + Aircraft findByRegistrationNumber(aircraft_registration.registration_number)
    }
    class AircraftRealtimeStatusUseCase <<@UseCase>> {
        + Aircraft execute(registration_number)
    }

    RegisterAircraftUseCase ..> AircraftRepository : findByRegistrationNumber()
    RegisterAircraftUseCase ..> Aircraft : finds >
}

@enduml