openapi: "3.1.0"
info:
  title: "US216 - Search Alternative Routes"
  version: "1.0.0"
servers:
  - url: "https://localhost:8080"
paths:
  /api/routes/alternatives:
    get:
      summary: "GET api/routes/alternatives"
      operationId: "searchAlternativeRoutes"
      parameters:
        - name: "origin"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "destination"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"