spring.application.name=AISafeFMS
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
jwt.secret=PSOFT12410081241131120085812109772026AndNowWeAreUpgradingToHS512WhichRequiresEvenMoreBytes12345
jwt.expiration=86400000
springdoc.api-docs.enabled=false