@startuml
title Register an Aircraft Model — POST /aircraft-model

autoactivate on

actor "Backoffice Operator" as BO
participant AircraftModelController
participant RegisterAircraftModelUseCase <<@UseCase>>
participant RegisterAircraftModelService <<Domain Service>>
participant AircraftModelRepository
participant AircraftManufacturerRepository

BO -> AircraftModelController : POST /aircraft-model\n{\n\tname: "Boeing 737",\n\tseating_capacity: 209,\n\tmax_range: 309.2,\n\tfuel_capacity: 80.97,\n\tcruising_speed: 200.0,\n\tmanufacturer_name: "Boeing"\n}

AircraftModelController -> AircraftModelController : extract username from JWT
alt "User has authorization"
    AircraftModelController -> RegisterAircraftModelUseCase : execute(name, seating_capacity, max_range, fuel_capacity, cruising_speed, manufacturer_name)
        RegisterAircraftModelUseCase -> AircraftManufacturerRepository : findByName(manufacturer_name)
        alt "The name manufacturer exists"
        AircraftManufacturerRepository --> RegisterAircraftModelUseCase : manufacturer_object
        RegisterAircraftModelUseCase -> RegisterAircraftModelService : register(name, seating_capacity, max_range, fuel_capacity, cruising_speed, manufacturer_object)
            RegisterAircraftModelService -> AircraftModelRepository : alreadyExists(name, seating_capacity, max_range, fuel_capacity, cruising_speed)
            AircraftModelRepository --> RegisterAircraftModelService : false
            RegisterAircraftModelService -> RegisterAircraftModelService : new AircraftModel(name, seating_capacity, max_range, fuel_capacity, cruising_speed, manufacturer_object)
        RegisterAircraftModelService --> RegisterAircraftModelUseCase : aircraft_model (unsaved)
        deactivate
        RegisterAircraftModelUseCase -> AircraftModelRepository : save(aircraft_model)
        AircraftModelRepository --> RegisterAircraftModelUseCase : aircraft_model (persisted)
    RegisterAircraftModelUseCase --> AircraftModelController : aircraft_model
AircraftModelController --> BO : 201 Created\n{ aircraft_model.name, _links.return }
        else "The manufacturer does not exist in the system"
AircraftModelController --> BO : 400 Bad Request\n{ message: "The request's data is malformed" }
        end

else "User does not have authorization"
AircraftModelController --> BO : 401 Unauthorized\n{ message: "The user does not have valid credentials for this action" }
end

@enduml