@startuml
'https://plantuml.com/sequence-diagram

autonumber

title View Aircraft Status in Real Time: Simplified Sequence Diagram

actor ATCC
participant ":System" as S

ATCC -> S: Types requested data to retrieve the aircraft's status\n(String registration_number)
S --> ATCC: Confirms the (in)sucess of the operation and shows the status

@enduml