@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

title Update Aircraft status: Domain Model

package "Aircraft Aggregate" {
    class Aircraft <<entity>> <<root>> {
        - manufacturing_date: Date
        - image: String
        - last_maintenance: Date
        - days_since_last_maintenance <<calculated>>: int
        - max_flight_hours_until_maintenance: int
        - max_days_until_maintenance: int
    }
    Aircraft o--> AircraftRegistration
    Aircraft o--> AircraftStatus

    class AircraftRegistration <<value object>> {
        - registration_number: String
    }
    class AircraftStatus <<enum>> {
        - AVAILABLE: int
        - IN_FLIGHT: int
        - INACTIVE: int
        - UNDER_MAINTENANCE: int
    }

}

@enduml