@startuml
autonumber

title Generate Statistics on the Busiest Airport: Simplified Sequence Diagram

actor "Backoffice Operator" as BO
participant ":System" as S

BO -> S: Asks to generate statistics on the busiest airport by number of routes
S --> BO: Shows the generated statistics

@enduml