@startuml
autonumber
title Register an Airport — POST /airports

autoactivate on

actor "Backoffice Operator" as BO
participant AirportController
participant RegisterAirportUseCase <<@UseCase>>
participant RegisterAirportService <<Domain Service>>
participant AirportRepository

BO -> AirportController : POST /airports\n{name, iata_code, airport_type, coordinates,\n airport_location,time_zone,operational_hours,\n runway_info, status , contact_info, \nterminals, gates,services, images}

AirportController -> AirportController : extract username from JWT
alt "User has authorization"
    AirportController -> RegisterAirportUseCase : execute(name, iata_code, airport_type, coordinates,\n airport_location,time_zone,operational_hours,\n runway_info, status , contact_info, \nterminals, gates,services, images)
        RegisterAirportUseCase -> AirportRepository : findByIataCode(LocationIdentifier)
        alt "The Airport's Iata Code exists"
        AirportRepository --> RegisterAirportUseCase: airport
        RegisterAirportUseCase -> RegisterAirportService: registerAirport(name, iata_code, airport_type, coordinates,\n airport_location,time_zone,operational_hours,\n runway_info, status , contact_info, \nterminals, gates,services, images)
            RegisterAirportService -> AirportRepository : isAvailable(LocationIdentifier)
            AirportRepository --> RegisterAirportService : true
            RegisterAirportService -> RegisterAirportService : new Airport(name, iata_code, airport_type, coordinates,\n airport_location,time_zone,operational_hours,\n runway_info, status , contact_info, \nterminals, gates,services, images)
        RegisterAirportService --> RegisterAirportUseCase : airport(unsaved)
        deactivate
        RegisterAirportUseCase -> AirportRepository : save(airport)
        AirportRepository --> RegisterAirportUseCase : airport (persisted)
    RegisterAirportUseCase --> AirportController : airport
AirportController --> BO : 201 Created\n{ airport.iata_code, _links.return }
    else "The airport does not exist in the system"
AirportController --> BO : 400 Bad Request\n{ message: "The request's data is malformed" }
    end

else "User does not have authorization"
AirportController --> BO : 401 Unauthorized\n{ message: "The user does not have valid credentials for this action" }
end

@enduml