@startuml
'https://plantuml.com/sequence-diagram

autonumber

title Update Airport Status: Simplified Sequence Diagram

actor "Backoffice Operator" as BO
participant ":System" as S

BO -> S: Asks to update an Airport's operational status (provides IATA code and new status)
S --> BO: Requests Iata Code and New Status

BO -> S:Types requested data
S --> BO: Updates the airport status

@enduml