@startuml
title Search Aircrafts by Model/Status/Manufacturing Year — GET /aircraft

autoactivate on

actor ATCC
participant AircraftController
participant FindAircraftByModelStatusManufactoringYearUseCase <<@UseCase>>
participant AircraftRepository

ATCC -> AircraftController : GET /aircraft\n\t{model_name: "Boeing 737"}\n\tOR\n\t{status: "AVAILABLE"}\n\tOR\n\t{year: 2025}

AircraftController -> AircraftController : extract username from JWT
alt "User has authorization"
    AircraftController -> FindAircraftByModelStatusManufactoringYearUseCase : execute(model_name / status / year)
        FindAircraftByModelStatusManufactoringYearUseCase -> AircraftRepository : findByModelName(name) / findByStatus(status) / findByManufactoringYear(year)
        alt "Aircrafts exist"
        AircraftRepository --> FindAircraftByModelStatusManufactoringYearUseCase : aircrafts
    FindAircraftByModelStatusManufactoringYearUseCase --> AircraftController : aircrafts
AircraftController --> ATCC : 200 OK\n{ list of the aircraft's registration numbers, _links.return }
        else "The aircraft does not exist in the system"
AircraftController --> ATCC : 400 Bad Request\n{ message: "The request's data is malformed" }
        end
else "User does not have authorization"
AircraftController --> ATCC : 401 Unauthorized\n{ message: "The user does not have valid credentials for this action" }
end

@enduml