@startuml
title View Airport's details by IATA code — GET /api/airports/{iata}

autoactivate on

actor "Backoffice\nOperator/ATCC" as BOATCC
participant AirportController
participant ViewAirportDetailsUseCase <<@UseCase>>
participant ViewAirportDetailsService <<Domain Service>>
participant AirportRepository
participant AirportAssembler

BOATCC -> AirportController : GET /api/airports/{iata}

AirportController -> AirportController : extract username from JWT
alt "User has authorization"
    AirportController -> ViewAirportDetailsUseCase : execute(iata_code)
        ViewAirportDetailsUseCase -> AirportRepository : findByIata(LocationIdentifier)
        alt "The airport exists"
            AirportRepository --> ViewAirportDetailsUseCase :
            ViewAirportDetailsUseCase -> ViewAirportDetailsService : getDetails(airport)
            ViewAirportDetailsService --> ViewAirportDetailsUseCase : airport_details
            ViewAirportDetailsUseCase --> AirportController : airport
            
            AirportController -> AirportAssembler : toModel(airport)
            return AirportDTO
            
            AirportController --> BOATCC : 200 OK
        else "The airport does not exist"
            AirportController --> BOATCC : 400 Bad Request\n{ message: "The request's data is malformed" }
        end

else "User does not have authorization"
    AirportController --> BOATCC : 403 Forbidden
end

@enduml