@startuml
title Add Airplane Certification to Airport — PUT /api/airports/{iata}/certifications

autoactivate on

actor "Backoffice Operator / ATCC" as BO
participant AirportController
participant CertifyAircraftUseCase <<@UseCase>>
participant CertifyAircraftService <<Domain Service>>
participant Airport <<Entity>>
participant AirportRepository
participant AircraftModelRepository
participant AirportAssembler

BO -> AirportController : PUT /api/airports/{iata}/certifications

AirportController -> AirportController : extract username from JWT
alt "User has authorization"
    AirportController -> CertifyAircraftUseCase : execute(iata, name)
        CertifyAircraftUseCase -> AirportRepository : findByIata(iata)

        alt "The airport exists"
            AirportRepository --> CertifyAircraftUseCase :

            CertifyAircraftUseCase -> AircraftModelRepository : findByName(name)

            alt "The aircraft model exists"
                AircraftModelRepository --> CertifyAircraftUseCase : List<AircraftModel>

                CertifyAircraftUseCase -> CertifyAircraftService : certify(airport, models.get(0))
                    CertifyAircraftService -> Airport : addCertifiedAircraftModel(model)
                    return
                return

                CertifyAircraftUseCase -> AirportRepository : save(airport)
                AirportRepository --> CertifyAircraftUseCase : airport (persisted)

                CertifyAircraftUseCase --> AirportController : airport
                
                AirportController -> AirportAssembler : toModel(airport)
                return AirportDTO
                
                AirportController --> BO : 200 OK\n

            else "The aircraft model does not exist"
                AirportController --> BO : 400 Bad Request\n
            end

        else "The airport does not exist"
            AirportController --> BO : 400 Bad Request\n
        end

else "User does not have authorization"
    AirportController --> BO : 403 Forbidden
end

@enduml