@startuml
'https://plantuml.com/class-diagram

title Register an Airport: Architecture — Class Diagram

package "Airport Aggregate" <<rectangle>> {
    class Airport <<root>> {
        - String name
        - LocationIdentifier iata_code
        - AirportType airport_type
        - Coordinates coordinates
        - AirportLocation airport_location
        - TimeZone time_zone
        - OperationalHours operational_hours
        - List<RunwayInfo> runway_info
        - AirportStatus status
        - List<ContactInfo> contact_info
        - List<AirportTerminal> terminals
        - List<AirportGate> gates
        - List<AirportService> services
        - List<String> images
        ---
        + Airport(name, iata_code, airport_type, coordinates, airport_location, time_zone, operational_hours, runway_info, status, contact_info, terminals, gates, services, images)
    }

    class RegisterAirportService <<Domain Service>> {
        ---
        + Airport registerAirport(String name, LocationIdentifier iata_code, AirportType airport_type, Coordinates coordinates,\n AirportLocation airport_location,TimeZone time_zone,OperationalHours operational_hours,\nList<RunwayInfo> runway_info,AirportStatus status ,List<ContactInfo> contact_info, \nList<AirportTerminal> terminals,List<AirportGate> gates,List<AirportService> services,List<String> images)
    }

    interface AirportRepository {
        + boolean isAvailable(LocationIdentifier)
        + Optional<Airport> findByIataCode(LocationIdentifier)
        + Airport save(Airport)
    }

    class RegisterAirportUseCase <<@UseCase>> {
        + Airport execute(String name, LocationIdentifier iata_code, AirportType airport_type, Coordinates coordinates,\n AirportLocation airport_location,TimeZone time_zone,OperationalHours operational_hours,\nList<RunwayInfo> runway_info,AirportStatus status ,List<ContactInfo> contact_info, \nList<AirportTerminal> terminals,List<AirportGate> gates,List<AirportService> services,List<String> images)
    }

RegisterAirportService ..> Airport : creates >
RegisterAirportUseCase ..> AirportRepository : save() >
RegisterAirportService ..> AirportRepository : isAvailable() >
RegisterAirportUseCase ..> RegisterAirportService : delegates to
RegisterAirportUseCase ..> AirportRepository : findByIataCode() >

}

@enduml
