openapi: "3.1.0"
info:
  title: "US209 - View Airport Routes"
  version: "1.0.0"
servers:
  - url: "https://localhost:8080"
paths:
  /api/airports/{iata}/routes:
    get:
      summary: "GET api/airports/{iata}/routes"
      operationId: "getAirportRoutes"
      parameters:
        - name: "iata"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"