@startuml
autonumber
title US117: View Total Maintenance Hours - Simplified Sequence Diagram

actor "ATCC" as User
participant ":System" as S

User -> S : Types requested data\n(String registrationNumber)
S --> User : Returns the total hours or confirms the (in)success of the operation
@enduml