@startuml
title List Active Routes — System Sequence Diagram

autoactivate on

actor "ATCC" as ATCC
participant "System" as System

ATCC -> System : GET /api/routes/active?sortBy={sort_by}

alt "User has authorization"
    System --> ATCC : 200 OK\n{ active_routes }

else "User does not have authorization"
    System --> ATCC : 401 Unauthorized\n{ message: "The user does not have valid credentials for this action" }
end

@enduml