@startuml
title View Airports Grouped By Region or Country — GET /api/airports?region={region}&country={country}

autoactivate on

actor "ATCC" as ATCC
participant AirportController
participant ViewGroupedAirportsUseCase <<@UseCase>>
participant ViewGroupedAirportsService <<Domain Service>>
participant AirportRepository
participant AirportAssembler

ATCC -> AirportController : GET /api/airports?region={region}&country={country}

AirportController -> AirportController : extract username from JWT
alt "User has authorization"
    AirportController -> ViewGroupedAirportsUseCase : execute(region, country)
        ViewGroupedAirportsUseCase -> ViewGroupedAirportsService : searchAirports(region, country)
            ViewGroupedAirportsService -> AirportRepository : groupByRegion() / groupByCountry()
            AirportRepository --> ViewGroupedAirportsService : list_of_airports
        ViewGroupedAirportsService --> ViewGroupedAirportsUseCase : list_of_airports
    ViewGroupedAirportsUseCase --> AirportController : list_of_airports

    alt "Return a List of Airports"
        loop "for each airport"
            AirportController -> AirportAssembler : toModel(airport)
            return airport_dto
        end
        AirportController --> ATCC : 200 OK
    else
        AirportController --> ATCC : 400 Bad Request\n{ message: "The request's data is malformed" }
    end

else "User does not have authorization"
    AirportController --> ATCC : 403 Forbidden
end

@enduml