@startuml
'https://plantuml.com/class-diagram

title Add Airplane Certification to Airport: Architecture — Class Diagram

package "Airport Aggregate" <<rectangle>> {
    class Airport <<root>> {
        - Set<AircraftModel> certified_models
        ---
    }

    interface AirportRepository {
        + Optional<Airport> findByIata(LocationIdentifier iata)
        + Airport save(Airport airport)
    }
}

package "Aircraft Aggregate" <<rectangle>> {
    class AircraftModel <<Aggregate Root>> {
            - String name
            + getName()
        }

    interface AircraftModelRepository {
        + List<AircraftModel> findByName(String name)
    }
}

class CertifyAircraftService <<Domain Service>> {
    + void certify(Airport airport, AircraftModel model)
}

class CertifyAircraftUseCase <<@UseCase>> {
    + Airport execute(LocationIdentifier iata, String name)
}

CertifyAircraftUseCase ..> AirportRepository : findByIata()\nsave()
CertifyAircraftUseCase ..> AircraftModelRepository : findByName()
CertifyAircraftUseCase ..> CertifyAircraftService : delegates to >
CertifyAircraftService ..> Airport : modifies >

@enduml