@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

package "Aircraft Agreggate" {
    class NonEmptyString <<value object>> {
        - string
    }
    class PositiveDouble <<value object>> {
        - number
    }
    class Aircraft <<entity>> <<root>> {
        - number_of_seats
        - manufactoring_date
        - image
        - last_maintenance
        - days_since_last_maintenance
        - max_flight_hours_until_maintenance
        - max_days_until_maintenance
    }
    Aircraft o--> AircraftRegistration
    Aircraft o--> AircraftStatus
    Aircraft o--> "3" PositiveDouble
    Aircraft o--> "N" NonEmptyString

    class AircraftRegistration <<value object>> {
        - registration_number
    }
    class AircraftStatus <<enum>> {
        - AVAILABLE
        - IN_FLIGHT
        - INACTIVE
        - UNDER_MAINTENANCE
    }
}

package "Airport Aggregate" {
    class NonEmptyString <<value object>> {
        - string
    }
    class PositiveDouble <<value object>> {
        - number
    }
    class Airport <<entity>> <<root>> {
        - images
    }
    Airport o--> LocationIdentifier
    Airport o--> Coordinates
    Airport o--> "N" RunwayInfo
    Airport o--> AirportStatus
    Airport o--> TimeZone
    Airport o--> "N" NonEmptyString
    Airport o--> OperationalHours
    Airport o--> ContactInfo

    class LocationIdentifier <<value object>> {
        - iata_code
    }
    class TimeZone <<entity>> {
        - abbreviation
        - utc_offset_minutes
        - gmt_offset_minutes
    }
    class OperationalHours <<value object>> {
        - opening_hours
        - closing_hours
    }
    class ContactInfo <<value object>> {
        - phone_number
    }
    class Coordinates <<value object>> {
        - longitude
        - longitude_direction
        - latitude
        - latitude_direction
    }
    class RunwayInfo <<entity>> {
        - orientation
    }
    RunwayInfo o--> NonEmptyString
    RunwayInfo o--> PositiveDouble
    class AirportStatus <<enum>> {
        - OPERATIONAL
        - CLOSED
        - UNDER_MAINTENANCE
    }
}

package "Route Aggregate" {
    class PositiveDouble <<value object>> {
        - number
    }
    class Route <<entity>> {
        - active
    }
    Route o--> RouteID
    Route o--> "4" PositiveDouble

    class RouteID <<value object>> {
        - id
    }
}

package "Flight Aggregate" {
    class Flight <<entity>> <<root>> {
        - scheduled_datetime
        - delayed_hours
    }
    Flight o--> FlightStatus
    Flight o--> FlightID

    class FlightStatus <<enum>> {
        - SCHEDULED
        - OCCURING
        - DELAYED
        - COMPLETED
        - CANCELED
    }
    class FlightID <<value object>> {
        - id
    }
}

package "Maintenance Aggregate" {
    class NonEmptyString <<value object>> {
        - string
    }
    class PositiveDouble <<value object>> {
        - number
    }
    class PartNumber <<value object>> {
        - part_number
    }
    class MaintenanceTemplateType <<enum>> {
        - INSPECTION
        - SCHEDULED_MAINTENANCE
        - OVERHAUL
        - MODIFICATION
    }
    class NumberedItem <<entity>> {
        - id
        - checklist
    }

    class MaintenanceTemplate <<entity>> {
        - applicable_models
    }
    MaintenanceTemplate o--> MaintenanceTemplateType
    MaintenanceTemplate o--> NonEmptyString
    MaintenanceTemplate o--> "N" NumberedItem
    MaintenanceTemplate o--> MaintenanceComponent
    MaintenanceTemplate o--> PositiveDouble

    class MaintenanceComponent <<enum>> {
        - ENGINE
        - AIRFRAME
        - AVIONICS
        - INTERIOR
        - EXTERIOR
    }

    class MaintenancePart <<entity>> {
        - description
        - stock_quantity
        - part_number
    }
    MaintenancePart o--> MaintenanceComponent
    MaintenancePart o--> NonEmptyString
    MaintenancePart o--> PartNumber

    class MaintenanceRecord <<entity>> <<root>> extends MaintenanceTemplate {
        - start_date
        - end_date <<calculated>>
        - completed
    }
    MaintenanceRecord ---> MaintenanceCompletionNotes
    MaintenanceRecord o--> NonEmptyString
    MaintenanceRecord o--> PositiveDouble
    class MaintenanceCompletionNotes <<value object>> {
        - completion_notes
    }
}

Airport -up> "N" Aircraft
Route --> "2" Airport
MaintenanceRecord --> Aircraft
Flight --> Route
Flight --> Aircraft

@enduml