@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0
hide methods

package "Aircraft Aggregate" {
    class Aircraft <<entity>> <<root>> {
        - manufacturing_date: Date
        - image: BufferedImage
        - last_maintenance: Date
        - fuel_capacity: double
        - cruising_speed: double
        - days_since_last_maintenance <<calculated>>: PositiveInteger
        - max_flight_hours_until_maintenance: PositiveInteger
        - max_days_until_maintenance: PositiveInteger
    }
    Aircraft o--> AircraftRegistration
    Aircraft o--> AircraftStatus
    Aircraft o--> AircraftManufacturer
    Aircraft o--> AircraftModel
    Aircraft o--> SeatingConfiguration

    class AircraftManufacturer <<value object>> {
        - name: String
    }

    class AircraftRegistration <<value object>> {
        - registration_number: String
    }
    class AircraftStatus <<enum>> {
        - AVAILABLE: int
        - IN_FLIGHT: int
        - INACTIVE: int
        - UNDER_MAINTENANCE: int
    }
    class AircraftModel <<value object>> {
        - name: String
        - seating_capacity: PositiveInteger
        - range: double
        - feature: Set<String>
    }

    class SeatingConfiguration <<value object>> {
        - economy_seats: PositiveInteger
        - premium_economy_seats: PositiveInteger
        - business_seats: PositiveInteger
        - first_seats: PositiveInteger
    }
}

package "Airport Aggregate" {
    class Airport <<entity>> <<root>> {
        - name: String
        - images: List<String>
    }
    Airport o--> LocationIdentifier
    Airport o--> AirportType
    Airport o--> Coordinates
    Airport o--> AirportLocation
    Airport o--> TimeZone
    Airport o--> OperationalHours
    Airport o--> AirportStatus
    Airport o--> "N" RunwayInfo
    Airport o--> "N" ContactInfo
    Airport o--> "N" AirportTerminal
    Airport o--> "N" AirportGate
    Airport o--> "N" AirportService

    class AirportLocation <<value object>> {
        - city: String
        - country: String
        - region: String
    }

    class AirportTerminal <<value object>> {
        - terminal: String
    }
    class AirportGate <<value object>> {
        - gate: String
    }
    class AirportService <<value object>> {
        - service: String
    }

    class AirportType <<value object>> {
        - name: String
        - description: String
    }
    class LocationIdentifier <<value object>> {
        - iata_code: String
    }

    class TimeZone <<entity>> {
        - abbreviation: String
        - utc_offset_minutes: PositiveInteger
        - gmt_offset_minutes: PositiveInteger
    }

    class OperationalHours <<value object>> {
        - opening_hours: PositiveInteger
        - closing_hours: PositiveInteger
    }

    class ContactInfo <<value object>> {
        - type: String
        - contact: String
        - description: String
    }
    ContactInfo o--> ContactInfoType
    class ContactInfoType <<enum>> {
        - EMAIL: int
        - PHONE_NUMBER: int
        - FAX_NUMBER: int
        - WEBSITE: int
        - MAILING_ADDRESS: int
    }

    class Coordinates <<value object>> {
        - longitude: double
        - longitude_direction: char
        - latitude: double
        - latitude_direction: char
    }

    class RunwayInfo <<entity>> {
        - name: String
        - length: double
    }
    RunwayInfo o--> Orientation

    class Orientation <<value object>> {
        - orientation: String
    }

    class AirportStatus <<enum>> {
        - OPERATIONAL: int
        - CLOSED: int
        - UNDER_MAINTENANCE: int
    }
}

package "Route Aggregate" {
    class Route <<entity>> <<root>> {
        - flight_time: double
        - flight_distance: double
        - min_aircraft_range: double
        - min_aircraft_capacity: double
        - active: boolean
    }
    Route o--> RouteID

    class RouteID <<value object>> {
        - id: String
    }
}

package "Flight Aggregate" {
    class Flight <<entity>> <<root>> {
        - scheduled_departure: Date
        - delayed_hours: double
        - effective_departure <<calculated>>: Date
        - scheduled_arrival <<calculated>>: Date
        - effective_arrival <<calculated>>: Date
    }
    Flight o--> FlightID
    Flight o--> FlightStatus

    class FlightID <<value object>> {
        - id: String
    }
    class FlightStatus <<enum>> {
        - SCHEDULED: int
        - OCCURRING: int
        - DELAYED: int
        - COMPLETED: int
        - CANCELED: int
    }
}

package "Maintenance Aggregate" {
    class MaintenanceTemplate <<entity>> {
        - name: String
        - cost: double
        - applicable_models: Set<String>
    }
    MaintenanceTemplate o--> MaintenanceTemplateType
    MaintenanceTemplate o--> Checklist
    MaintenanceTemplate o--> MaintenancePart

    class MaintenanceTemplateType <<enum>> {
        - INSPECTION: int
        - SCHEDULED_MAINTENANCE: int
        - OVERHAUL: int
        - MODIFICATION: int
    }
    class Checklist <<entity>> {}
    Checklist --> "N" NumberedItem
    class NumberedItem <<value object>> {
        - id: PositiveInteger
        - task: String
    }

    class MaintenancePart <<entity>> {
        - name: String
        - description: String
        - stock_quantity: PositiveInteger
    }
    MaintenancePart o--> MaintenanceComponent
    MaintenancePart o--> PartNumber
    class PartNumber <<value object>> {
        - part_number: String
    }
    class MaintenanceComponent <<enum>> {
        - ENGINE: int
        - AIRFRAME: int
        - AVIONICS: int
        - INTERIOR: int
        - EXTERIOR: int
    }

    class MaintenanceRecord <<entity>> <<root>> extends MaintenanceTemplate {
        - description: String
        - expected_duration: double
        - start_date: Date
        - end_date <<calculated>>: Date
        - completed: boolean
    }
    MaintenanceRecord ---> MaintenanceCompletionNotes
    class MaintenanceCompletionNotes <<value object>> {
        - completion_notes: String
    }
}

Airport -up> "N" Aircraft
Route --> "2" Airport
MaintenanceRecord --> Aircraft
Flight --> Route
Flight --> Aircraft

@enduml