@startuml
'https://plantuml.com/class-diagram

Aircraft <<entity>>
Airport <<entity>>
Route <<entity>>
MaintenanceRecord <<entity>>

PositiveInt <<value object>>
AircraftRegistration <<value object>>
AircraftStatus <<value object>>/<<enum>>
LocationIdentifier <<value object>>
Coordinates <<value object>>
RunwayInfo <<value object>>
AirportStatus <<value object>>/<<enum>>
RouteID <<value object>>
PositiveDouble <<value object>>
MaintenanceTemplate <<entity>>/<<value object>>

@enduml