openapi: "3.1.0"
info:
  title: "US109 - Update Airport Status"
  version: "1.0.0"
servers:
  - url: "https://localhost:8080"
paths:
  /api/airports/{iata}:
    patch:
      summary: "PATCH api/airports/{iata}"
      operationId: "updateAirportStatus"
      parameters:
        - name: "iata"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateAirportStatusRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    UpdateAirportStatusRequest:
      type: "object"
      properties:
        status: { type: "string" }